openapi: 3.0.3
info:
  title: Broker Operations Sync API (Extension Internal Abstraction)
  version: 1.0.0
  description: Internal abstraction layer for jsRofex broker operations retrieval used by the extension.
servers:
  - url: https://broker.example.com/api
    description: Placeholder base URL (replace with actual jsRofex endpoint)
paths:
  /auth/login:
    post:
      summary: Authenticate user and obtain session token
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required: [username, password]
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  expiry:
                    type: integer
        '401':
          description: Invalid credentials
  /auth/refresh:
    post:
      summary: Refresh session token
      operationId: refreshToken
      responses:
        '200':
          description: Token refreshed
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  expiry:
                    type: integer
        '401':
          description: Token expired / invalid
  /operations:
    get:
      summary: List operations for current trading day
      operationId: listOperations
      parameters:
        - in: query
          name: pageToken
          schema:
            type: string
          required: false
        - in: query
          name: date
          schema:
            type: string
            format: date
          required: false
      responses:
        '200':
          description: Operations page
          headers:
            X-Next-Page-Token:
              schema:
                type: string
              description: Token for next page if present
            X-Estimated-Total:
              schema:
                type: integer
              description: Estimated total operations count for progress feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  operations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Operation'
        '401':
          description: Unauthorized
        '429':
          description: Rate limited
        '500':
          description: Server error
components:
  schemas:
    Operation:
      type: object
      properties:
        order_id:
          type: string
          nullable: true
        operation_id:
          type: string
          nullable: true
        symbol:
          type: string
        optionType:
          type: string
          enum: [call, put, stock]
        action:
          type: string
          enum: [buy, sell]
        quantity:
          type: integer
        price:
          type: number
          format: double
        tradeTimestamp:
          type: integer
          description: Epoch milliseconds
        strike:
          type: number
          nullable: true
        expirationDate:
          type: string
          format: date
          nullable: true
        sourceReferenceId:
          type: string
          nullable: true
        status:
          type: string
          nullable: true
          enum: [open, closed, revised, canceled]
      required: [symbol, optionType, action, quantity, price, tradeTimestamp]
