name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-to-github-pages.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ChuchoCoder/chuchocoder.github.io
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: target-repo
          fetch-depth: 0

      - name: Clean target repository
        run: |
          cd target-repo
          # Remove old files but keep README.md and .git
          rm -f index.html vite.svg
          rm -rf assets

      - name: Copy new build files
        run: |
          cp -r frontend/dist/* target-repo/

      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to deploy"
          else
            git commit -m "Deploy frontend from procesador-opciones@${{ github.sha }}"
            git push
          fi
